package es.netkia.script;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public abstract class Script implements IScript {
	public static final String AUTO_INCREMENT = "GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE";
	public static final String BAD_COLUMN_SYNTAX = "[ BAD_COLUMN_SYNTAX ]";
	public static final String TYPE_NOT_FOUND = "[ TYPE_NOT_FOUND ]";
	public static final String EMPTY = "[ EMPTY ]";
	
	protected String schema;
	protected String name;
	protected String tablespace;
	protected ArrayList<String> columns;
	protected HashMap<String,String> properties;
	
	public Script(List<String> lines, HashMap<String,String> properties) {
		this.schema = lines.get(0);
		this.name = lines.get(1);
		this.tablespace = lines.get(2);
		this.properties = properties;
		this.columns = new ArrayList<String>();
		
		int flag = 0;
		for(String line : lines) {
			if(flag == 1) this.columns.add(line);
			if(line.equals("#")) flag = 1;
		}
	}
}
